// <auto-generated />
namespace MVC_FirstProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedMembership : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedMembership));
        
        string IMigrationMetadata.Id
        {
            get { return "201806191657065_addedMembership"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
